### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by mikerouleau** [mikerouleau/CochleaSolver.jl#7]
### Documentation
- [ ] Document PACE usage #5
- [ ] Document local usage
- [ ] Document required variables for each excitation
- [ ] Document types

### Features
- [ ] Expose DiffEq Solver to MATLAB #4 
- [ ] Specify output file name #6 

### Other
- [ ] Unit tests #3 
- [ ] Complete PACE verification

**Comment by mikerouleau** [comment]
Removing some documentation requirements for now - waiting for upstream docs.

**Comment by mikerouleau** [comment]
Waiting for CI to finish on #26, then go
